import { NextRequest, NextResponse } from "next/server";
import yahooFinance from "yahoo-finance2";

// Comprehensive NSE stock symbols - covers penny to large cap
const NSE_SYMBOLS = [
  // NIFTY 50
  "ADANIENT.NS",
  "ADANIPORTS.NS",
  "APOLLOHOSP.NS",
  "ASIANPAINT.NS",
  "AXISBANK.NS",
  "BAJAJ-AUTO.NS",
  "BAJFINANCE.NS",
  "BAJAJFINSV.NS",
  "BHARTIARTL.NS",
  "BPCL.NS",
  "BRITANNIA.NS",
  "CIPLA.NS",
  "COALINDIA.NS",
  "DIVISLAB.NS",
  "DRREDDY.NS",
  "EICHERMOT.NS",
  "GRASIM.NS",
  "HCLTECH.NS",
  "HDFCBANK.NS",
  "HDFCLIFE.NS",
  "HEROMOTOCO.NS",
  "HINDALCO.NS",
  "HINDUNILVR.NS",
  "ICICIBANK.NS",
  "INDUSINDBK.NS",
  "INFY.NS",
  "ITC.NS",
  "JSWSTEEL.NS",
  "KOTAKBANK.NS",
  "LT.NS",
  "LTIM.NS",
  "M&M.NS",
  "MARUTI.NS",
  "NESTLEIND.NS",
  "NTPC.NS",
  "ONGC.NS",
  "POWERGRID.NS",
  "RELIANCE.NS",
  "SBILIFE.NS",
  "SBIN.NS",
  "SHRIRAMFIN.NS",
  "SUNPHARMA.NS",
  "TATACONSUM.NS",
  "TATAMOTORS.NS",
  "TATASTEEL.NS",
  "TCS.NS",
  "TECHM.NS",
  "TITAN.NS",
  "ULTRACEMCO.NS",
  "WIPRO.NS",
  // NIFTY NEXT 50
  "ABB.NS",
  "ADANIGREEN.NS",
  "ADANITRANS.NS",
  "AMBUJACEM.NS",
  "AUROPHARMA.NS",
  "BAJAJHLDNG.NS",
  "BANKBARODA.NS",
  "BERGEPAINT.NS",
  "BOSCHLTD.NS",
  "CANBK.NS",
  "CHOLAFIN.NS",
  "COLPAL.NS",
  "DABUR.NS",
  "DMART.NS",
  "GAIL.NS",
  "GODREJCP.NS",
  "HAVELLS.NS",
  "ICICIGI.NS",
  "ICICIPRULI.NS",
  "INDIGO.NS",
  "IOC.NS",
  "IRCTC.NS",
  "JUBLFOOD.NS",
  "LICHSGFIN.NS",
  "LUPIN.NS",
  "MCDOWELL-N.NS",
  "MOTHERSON.NS",
  "MUTHOOTFIN.NS",
  "NAUKRI.NS",
  "PAGEIND.NS",
  "PIDILITIND.NS",
  "PIIND.NS",
  "PNB.NS",
  "RECLTD.NS",
  "SAIL.NS",
  "SHREECEM.NS",
  "SIEMENS.NS",
  "SRF.NS",
  "TATACOMM.NS",
  "TATAPOWER.NS",
  "TORNTPHARM.NS",
  "UBL.NS",
  "VEDL.NS",
  "VOLTAS.NS",
  "WHIRLPOOL.NS",
  // Mid Cap
  "ABCAPITAL.NS",
  "AFFLE.NS",
  "AKZOINDIA.NS",
  "ALKEM.NS",
  "ALOKINDS.NS",
  "AMBER.NS",
  "ANGELONE.NS",
  "APOLLOTYRE.NS",
  "ASHOKLEY.NS",
  "ASTRAL.NS",
  "ATUL.NS",
  "AUROBINAPHAR.NS",
  "AVANTIFEED.NS",
  "BATA.NS",
  "BHEL.NS",
  "BIKAJI.NS",
  "BLUESTARCO.NS",
  "BRIGADE.NS",
  "BSE.NS",
  "CAMS.NS",
  "CANFINHOME.NS",
  "CDSL.NS",
  "CENTURYPLY.NS",
  "CESC.NS",
  "CHAMBLFERT.NS",
  "CLEAN.NS",
  "CONCORDBIO.NS",
  "CRISIL.NS",
  "CROMPTON.NS",
  "CYIENT.NS",
  "DATAPATTNS.NS",
  "DELHIVERY.NS",
  "DEVYANI.NS",
  "DIXON.NS",
  "DPDIRECT.NS",
  "ELGIEQUIP.NS",
  "EMAMILTD.NS",
  "ESCORTS.NS",
  "EXIDEIND.NS",
  "FINEORG.NS",
  "FINPIPE.NS",
  "FLUOROCHEM.NS",
  "GLENMARK.NS",
  "GNFC.NS",
  "GODREJPROP.NS",
  "GRANULES.NS",
  "GRINDWELL.NS",
  "GSPL.NS",
  "HAPPSTMNDS.NS",
  "HFCL.NS",
  "HINDPETRO.NS",
  "HONAUT.NS",
  "IDFCFIRSTB.NS",
  "IFCI.NS",
  "IGL.NS",
  "INDIANB.NS",
  "INDIAMART.NS",
  "IRCON.NS",
  "JBCHEPHARM.NS",
  "JINDALSAW.NS",
  "JUBILANT.NS",
  "JUBLPHARMA.NS",
  "JUSTDIAL.NS",
  "KAJARIACER.NS",
  "KANSAINER.NS",
  "KARURVYSYA.NS",
  "KEC.NS",
  "KPITTECH.NS",
  "L&TFH.NS",
  "LATENTVIEW.NS",
  "LICI.NS",
  "LINDEINDIA.NS",
  "LUXIND.NS",
  "MAHINDCIE.NS",
  "MARICO.NS",
  "MFSL.NS",
  "MIDHANI.NS",
  "MINDTREE.NS",
  "MPHASIS.NS",
  "MRF.NS",
  "NATIONALUM.NS",
  "NAVINFLUOR.NS",
  "NBCC.NS",
  "NCC.NS",
  "NHPC.NS",
  "NILKAMAL.NS",
  "NLCINDIA.NS",
  "NYKAA.NS",
  "OBEROIRLTY.NS",
  "OIL.NS",
  "OLECTRA.NS",
  "ORIENTELEC.NS",
  "PAYTM.NS",
  "PERSISTENT.NS",
  "PETRONET.NS",
  "PFIZER.NS",
  "POLYMED.NS",
  "POONAWALLA.NS",
  "PRESTIGE.NS",
  "PRINCEPIPE.NS",
  "PROPTIGER.NS",
  "PSUBBANKA.NS",
  "PVR.NS",
  "RAIN.NS",
  "RAJRATAN.NS",
  "RATNAMANI.NS",
  "RAYMOND.NS",
  "RBLBANK.NS",
  "REDINGTON.NS",
  "RHIM.NS",
  "ROUTE.NS",
  "SANOFI.NS",
  "SAPPHIRE.NS",
  "SCHAEFFLER.NS",
  "SEQUENT.NS",
  "SKFINDIA.NS",
  "SOBHA.NS",
  "SONATSOFTW.NS",
  "SPARC.NS",
  "SUDARSCHEM.NS",
  "SUPREMEIND.NS",
  "SUVENPHAR.NS",
  "SYNGENE.NS",
  "TANLA.NS",
  "TATAELXSI.NS",
  "TATATECH.NS",
  "TEAMLEASE.NS",
  "THERMAX.NS",
  "TIINDIA.NS",
  "TIMKEN.NS",
  "TORNTPOWER.NS",
  "TRENT.NS",
  "TRIDENT.NS",
  "TRITURBINE.NS",
  "TVSMOTORS.NS",
  "UBL.NS",
  "UJJIVANSF.NS",
  "ULTRACEMCO.NS",
  "UNIONBANK.NS",
  "UNIPARTS.NS",
  "USHAMART.NS",
  "UTIAMC.NS",
  "VAIBHAVGBL.NS",
  "VALIANTLAB.NS",
  "VBL.NS",
  "VEDL.NS",
  "VIJAYA.NS",
  "VSTIND.NS",
  "WOCKPHARMA.NS",
  "YESBANK.NS",
  "ZENSARTECH.NS",
  "ZOMATO.NS",
  "ZYDUSLIFE.NS",
];

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const type = searchParams.get("type") || "list";

  if (type === "list") {
    return NextResponse.json(NSE_SYMBOLS);
  }

  if (type === "news") {
    const symbol = searchParams.get("symbol") || "RELIANCE.NS";
    try {
      const results = await yahooFinance.search(symbol, { newsCount: 10 });
      const news = ((results as any).news || []).map((n: any) => ({
        title: n.title,
        description: n.summary || n.title,
        url: n.link,
        source: n.publisher,
        publishedAt: n.providerPublishTime
          ? new Date(n.providerPublishTime * 1000).toISOString()
          : new Date().toISOString(),
      }));
      return NextResponse.json(news);
    } catch {
      return NextResponse.json([]);
    }
  }

  return NextResponse.json({ error: "Invalid" }, { status: 400 });
}
