// lib/stockUniverse.ts
// Comprehensive NSE stock universe organized by price tier
// Penny: ₹1–399 | Mid: ₹400–999 | High: ₹1000+
// 500+ symbols covering NIFTY500 + popular SME/penny stocks

export interface StockMeta {
  symbol: string;
  name: string;
  sector: string;
}

// ── PENNY STOCKS (typically ₹1–₹399) ─────────────────────────────────────────
export const PENNY_STOCKS: StockMeta[] = [
  // PSU Banks & Finance
  { symbol: 'YESBANK.NS', name: 'Yes Bank', sector: 'Banking' },
  { symbol: 'PNB.NS', name: 'Punjab National Bank', sector: 'Banking' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda', sector: 'Banking' },
  { symbol: 'CANBK.NS', name: 'Canara Bank', sector: 'Banking' },
  { symbol: 'UNIONBANK.NS', name: 'Union Bank of India', sector: 'Banking' },
  { symbol: 'UCOBANK.NS', name: 'UCO Bank', sector: 'Banking' },
  { symbol: 'CENTRALBK.NS', name: 'Central Bank of India', sector: 'Banking' },
  { symbol: 'IOB.NS', name: 'Indian Overseas Bank', sector: 'Banking' },
  { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra', sector: 'Banking' },
  { symbol: 'INDIANB.NS', name: 'Indian Bank', sector: 'Banking' },
  { symbol: 'BANKINDIA.NS', name: 'Bank of India', sector: 'Banking' },
  { symbol: 'RBLBANK.NS', name: 'RBL Bank', sector: 'Banking' },
  { symbol: 'KARURVYSYA.NS', name: 'Karur Vysya Bank', sector: 'Banking' },
  { symbol: 'FEDERALBNK.NS', name: 'Federal Bank', sector: 'Banking' },
  { symbol: 'SOUTHBANK.NS', name: 'South Indian Bank', sector: 'Banking' },
  { symbol: 'KTKBANK.NS', name: 'Karnataka Bank', sector: 'Banking' },
  { symbol: 'DCBBANK.NS', name: 'DCB Bank', sector: 'Banking' },
  { symbol: 'J&KBANK.NS', name: 'J&K Bank', sector: 'Banking' },
  { symbol: 'UJJIVANSF.NS', name: 'Ujjivan Small Finance Bank', sector: 'Banking' },
  { symbol: 'ESAFSFB.NS', name: 'ESAF Small Finance Bank', sector: 'Banking' },
  // Power & Infra
  { symbol: 'NHPC.NS', name: 'NHPC Ltd', sector: 'Power' },
  { symbol: 'SJVN.NS', name: 'SJVN Ltd', sector: 'Power' },
  { symbol: 'IRCON.NS', name: 'Ircon International', sector: 'Infrastructure' },
  { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam', sector: 'Infrastructure' },
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance', sector: 'Finance' },
  { symbol: 'NBCC.NS', name: 'NBCC India', sector: 'Construction' },
  { symbol: 'HFCL.NS', name: 'HFCL Ltd', sector: 'Telecom' },
  { symbol: 'STLTECH.NS', name: 'Sterlite Technologies', sector: 'Telecom' },
  { symbol: 'RAILTEL.NS', name: 'RailTel Corporation', sector: 'Telecom' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics', sector: 'Defence' },
  { symbol: 'BEML.NS', name: 'BEML Ltd', sector: 'Defence' },
  { symbol: 'MIDHANI.NS', name: 'Mishra Dhatu Nigam', sector: 'Defence' },
  // Metals & Mining
  { symbol: 'SAIL.NS', name: 'SAIL', sector: 'Steel' },
  { symbol: 'NATIONALUM.NS', name: 'National Aluminium', sector: 'Metals' },
  { symbol: 'NMDC.NS', name: 'NMDC Ltd', sector: 'Mining' },
  { symbol: 'MOIL.NS', name: 'MOIL Ltd', sector: 'Mining' },
  { symbol: 'HINDCOPPER.NS', name: 'Hindustan Copper', sector: 'Metals' },
  { symbol: 'GMRINFRA.NS', name: 'GMR Infrastructure', sector: 'Infrastructure' },
  // IT & Tech
  { symbol: 'RATEGAIN.NS', name: 'RateGain Travel Tech', sector: 'IT' },
  { symbol: 'TANLA.NS', name: 'Tanla Platforms', sector: 'IT' },
  { symbol: 'SUBEXLIMITED.NS', name: 'Subex Ltd', sector: 'IT' },
  { symbol: 'ZENSARTECH.NS', name: 'Zensar Technologies', sector: 'IT' },
  { symbol: 'MASTEK.NS', name: 'Mastek Ltd', sector: 'IT' },
  { symbol: 'NELCO.NS', name: 'NELCO Ltd', sector: 'IT' },
  // Pharma & Healthcare
  { symbol: 'WOCKPHARMA.NS', name: 'Wockhardt', sector: 'Pharma' },
  { symbol: 'GRANULES.NS', name: 'Granules India', sector: 'Pharma' },
  { symbol: 'SEQUENT.NS', name: 'SeQuent Scientific', sector: 'Pharma' },
  { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma', sector: 'Pharma' },
  { symbol: 'SHILPAMED.NS', name: 'Shilpa Medicare', sector: 'Pharma' },
  { symbol: 'JBCHEPHARM.NS', name: 'JB Chemicals', sector: 'Pharma' },
  // Others
  { symbol: 'TRIDENT.NS', name: 'Trident Ltd', sector: 'Textiles' },
  { symbol: 'RAYMOND.NS', name: 'Raymond Ltd', sector: 'Textiles' },
  { symbol: 'IDBI.NS', name: 'IDBI Bank', sector: 'Banking' },
  { symbol: 'IFCI.NS', name: 'IFCI Ltd', sector: 'Finance' },
  { symbol: 'PFC.NS', name: 'Power Finance Corp', sector: 'Finance' },
  { symbol: 'RECLTD.NS', name: 'REC Ltd', sector: 'Finance' },
  { symbol: 'RITES.NS', name: 'RITES Ltd', sector: 'Infrastructure' },
  { symbol: 'MTNL.NS', name: 'MTNL', sector: 'Telecom' },
  { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank', sector: 'Banking' },
  { symbol: 'SUZLON.NS', name: 'Suzlon Energy', sector: 'Power' },
  { symbol: 'INDIABULLS.NS', name: 'Indiabulls Housing Finance', sector: 'Finance' },
  { symbol: 'SUNTV.NS', name: 'Sun TV Network', sector: 'Media' },
  { symbol: 'PFIZER.NS', name: 'Pfizer India', sector: 'Pharma' },
  { symbol: 'MRPL.NS', name: 'MRPL', sector: 'Oil & Gas' },
  { symbol: 'ONGC.NS', name: 'ONGC', sector: 'Oil & Gas' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corp', sector: 'Oil & Gas' },
  { symbol: 'BPCL.NS', name: 'BPCL', sector: 'Oil & Gas' },
  { symbol: 'HINDPETRO.NS', name: 'HPCL', sector: 'Oil & Gas' },
  { symbol: 'GAIL.NS', name: 'GAIL India', sector: 'Gas' },
  { symbol: 'COALINDIA.NS', name: 'Coal India', sector: 'Mining' },
  { symbol: 'NTPC.NS', name: 'NTPC', sector: 'Power' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corp', sector: 'Power' },
  { symbol: 'TATAPOWER.NS', name: 'Tata Power', sector: 'Power' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy', sector: 'Power' },
  { symbol: 'ADANIPOWER.NS', name: 'Adani Power', sector: 'Power' },
  { symbol: 'TORNTPOWER.NS', name: 'Torrent Power', sector: 'Power' },
  { symbol: 'CESC.NS', name: 'CESC Ltd', sector: 'Power' },
  { symbol: 'JSWENERGY.NS', name: 'JSW Energy', sector: 'Power' },
  { symbol: 'RENUKA.NS', name: 'Shree Renuka Sugars', sector: 'Sugar' },
  { symbol: 'BALRAMCHIN.NS', name: 'Balrampur Chini Mills', sector: 'Sugar' },
  { symbol: 'DHAMPUR.NS', name: 'Dhampur Sugar Mills', sector: 'Sugar' },
  { symbol: 'TRIVENI.NS', name: 'Triveni Engineering', sector: 'Sugar' },
  { symbol: 'CHAMBLFERT.NS', name: 'Chambal Fertilizers', sector: 'Fertilizers' },
  { symbol: 'GNFC.NS', name: 'GNFC', sector: 'Chemicals' },
  { symbol: 'NFL.NS', name: 'National Fertilizers', sector: 'Fertilizers' },
  { symbol: 'RCF.NS', name: 'Rashtriya Chemicals', sector: 'Fertilizers' },
  { symbol: 'GSPL.NS', name: 'Gujarat State Petronet', sector: 'Gas' },
  { symbol: 'PETRONET.NS', name: 'Petronet LNG', sector: 'Gas' },
  { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite', sector: 'Chemicals' },
  { symbol: 'TATACHEM.NS', name: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'ALOKINDS.NS', name: 'Alok Industries', sector: 'Textiles' },
  { symbol: 'WELSPUNIND.NS', name: 'Welspun India', sector: 'Textiles' },
  { symbol: 'VEDL.NS', name: 'Vedanta Ltd', sector: 'Metals' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'BANKOFMAHARASHTRA.NS', name: 'Bank of Maharashtra', sector: 'Banking' },
  { symbol: 'OLECTRA.NS', name: 'Olectra Greentech', sector: 'EV' },
];

// ── MID STOCKS (₹400–₹999) ────────────────────────────────────────────────────
export const MID_STOCKS: StockMeta[] = [
  { symbol: 'SBIN.NS', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', sector: 'Banking' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Finance', sector: 'Finance' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', sector: 'Finance' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', sector: 'Finance' },
  { symbol: 'LICHSGFIN.NS', name: 'LIC Housing Finance', sector: 'Finance' },
  { symbol: 'CANFINHOME.NS', name: 'Can Fin Homes', sector: 'Finance' },
  { symbol: 'POONAWALLA.NS', name: 'Poonawalla Fincorp', sector: 'Finance' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance', sector: 'Insurance' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', sector: 'Insurance' },
  { symbol: 'ICICIGI.NS', name: 'ICICI General Insurance', sector: 'Insurance' },
  { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life', sector: 'Insurance' },
  { symbol: 'MFSL.NS', name: 'Max Financial Services', sector: 'Insurance' },
  // IT
  { symbol: 'WIPRO.NS', name: 'Wipro Ltd', sector: 'IT' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'INFOSYS.NS', name: 'Infosys Ltd', sector: 'IT' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy', sector: 'IT' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree', sector: 'IT' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis Ltd', sector: 'IT' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems', sector: 'IT' },
  { symbol: 'COFORGE.NS', name: 'Coforge Ltd', sector: 'IT' },
  { symbol: 'CYIENT.NS', name: 'Cyient Ltd', sector: 'IT' },
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies', sector: 'IT' },
  { symbol: 'LATENTVIEW.NS', name: 'LatentView Analytics', sector: 'IT' },
  { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds', sector: 'IT' },
  // Pharma
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical', sector: 'Pharma' },
  { symbol: 'CIPLA.NS', name: 'Cipla Ltd', sector: 'Pharma' },
  { symbol: 'LUPIN.NS', name: 'Lupin Ltd', sector: 'Pharma' },
  { symbol: 'DRREDDY.NS', name: 'Dr Reddy\'s Lab', sector: 'Pharma' },
  { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma', sector: 'Pharma' },
  { symbol: 'BIOCON.NS', name: 'Biocon Ltd', sector: 'Pharma' },
  { symbol: 'GLENMARK.NS', name: 'Glenmark Pharma', sector: 'Pharma' },
  { symbol: 'IPCALAB.NS', name: 'IPCA Laboratories', sector: 'Pharma' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharma', sector: 'Pharma' },
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories', sector: 'Pharma' },
  { symbol: 'SANOFI.NS', name: 'Sanofi India', sector: 'Pharma' },
  { symbol: 'PFIZER.NS', name: 'Pfizer India', sector: 'Pharma' },
  // Auto
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'ASHOKLEY.NS', name: 'Ashok Leyland', sector: 'Auto' },
  { symbol: 'APOLLOTYRE.NS', name: 'Apollo Tyres', sector: 'Auto' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries', sector: 'Auto' },
  { symbol: 'EXIDEIND.NS', name: 'Exide Industries', sector: 'Auto' },
  { symbol: 'MOTHERSON.NS', name: 'Samvardhana Motherson', sector: 'Auto' },
  { symbol: 'TVSMOTORS.NS', name: 'TVS Motor Company', sector: 'Auto' },
  { symbol: 'TIINDIA.NS', name: 'Tube Investments', sector: 'Auto' },
  // FMCG
  { symbol: 'ITC.NS', name: 'ITC Ltd', sector: 'FMCG' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer', sector: 'FMCG' },
  { symbol: 'DABUR.NS', name: 'Dabur India', sector: 'FMCG' },
  { symbol: 'MARICO.NS', name: 'Marico Ltd', sector: 'FMCG' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products', sector: 'FMCG' },
  { symbol: 'EMAMILTD.NS', name: 'Emami Ltd', sector: 'FMCG' },
  { symbol: 'JYOTHYLAB.NS', name: 'Jyothy Labs', sector: 'FMCG' },
  // Cement
  { symbol: 'ACC.NS', name: 'ACC Ltd', sector: 'Cement' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements', sector: 'Cement' },
  { symbol: 'RAMCOCEM.NS', name: 'Ramco Cements', sector: 'Cement' },
  { symbol: 'DALMIACEMB.NS', name: 'Dalmia Bharat', sector: 'Cement' },
  { symbol: 'BIRLACEM.NS', name: 'Birla Corporation', sector: 'Cement' },
  // Infra & Construction
  { symbol: 'LT.NS', name: 'Larsen & Toubro', sector: 'Infrastructure' },
  { symbol: 'KEC.NS', name: 'KEC International', sector: 'Infrastructure' },
  { symbol: 'NCC.NS', name: 'NCC Ltd', sector: 'Construction' },
  { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises', sector: 'Real Estate' },
  { symbol: 'SOBHA.NS', name: 'Sobha Ltd', sector: 'Real Estate' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates', sector: 'Real Estate' },
  { symbol: 'PHOENIXLTD.NS', name: 'Phoenix Mills', sector: 'Real Estate' },
  // Others
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'ZOMATO.NS', name: 'Zomato Ltd', sector: 'Consumer Tech' },
  { symbol: 'IRCTC.NS', name: 'IRCTC', sector: 'Travel' },
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation', sector: 'Aviation' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies', sector: 'Electronics' },
  { symbol: 'AMBER.NS', name: 'Amber Enterprises', sector: 'Electronics' },
  { symbol: 'KAYNES.NS', name: 'Kaynes Technology', sector: 'Electronics' },
  { symbol: 'ANGELONE.NS', name: 'Angel One', sector: 'Finance' },
  { symbol: 'CDSL.NS', name: 'CDSL', sector: 'Finance' },
  { symbol: 'BSE.NS', name: 'BSE Ltd', sector: 'Finance' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge (Naukri)', sector: 'Consumer Tech' },
  { symbol: 'JUBLFOOD.NS', name: 'Jubilant Foodworks', sector: 'QSR' },
  { symbol: 'DEVYANI.NS', name: 'Devyani International', sector: 'QSR' },
  { symbol: 'WESTLIFE.NS', name: 'Westlife Foodworld', sector: 'QSR' },
  { symbol: 'DMART.NS', name: 'Avenue Supermarts', sector: 'Retail' },
  { symbol: 'TRENT.NS', name: 'Trent Ltd', sector: 'Retail' },
  { symbol: 'PATANJALIFO.NS', name: 'Patanjali Foods', sector: 'FMCG' },
  { symbol: 'HAVELLS.NS', name: 'Havells India', sector: 'Electricals' },
  { symbol: 'VOLTAS.NS', name: 'Voltas Ltd', sector: 'Electricals' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Consumer', sector: 'Electricals' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India', sector: 'Electricals' },
  { symbol: 'KEI.NS', name: 'KEI Industries', sector: 'Electricals' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', sector: 'IT' },
  { symbol: 'TATACOMMUNICATIONS.NS', name: 'Tata Communications', sector: 'Telecom' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel', sector: 'Steel' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', sector: 'Steel' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel & Power', sector: 'Steel' },
  { symbol: 'WELCORP.NS', name: 'Welspun Corp', sector: 'Steel' },
  { symbol: 'RATNAMANI.NS', name: 'Ratnamani Metals', sector: 'Steel' },
  { symbol: 'SIEMENS.NS', name: 'Siemens India', sector: 'Engineering' },
  { symbol: 'HONAUT.NS', name: 'Honeywell Automation', sector: 'Engineering' },
  { symbol: 'THERMAX.NS', name: 'Thermax Ltd', sector: 'Engineering' },
  { symbol: 'ABB.NS', name: 'ABB India', sector: 'Engineering' },
];

// ── HIGH VALUE STOCKS (₹1000+) ───────────────────────────────────────────────
export const HIGH_STOCKS: StockMeta[] = [
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', sector: 'Conglomerate' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'INFOSYS.NS', name: 'Infosys Ltd', sector: 'IT' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro', sector: 'Engineering' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', sector: 'Finance' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki', sector: 'Auto' },
  { symbol: 'TITAN.NS', name: 'Titan Company', sector: 'Jewellery' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharma', sector: 'Pharma' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', sector: 'Paints' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', sector: 'Finance' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', sector: 'Conglomerate' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports', sector: 'Ports' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'WIPRO.NS', name: 'Wipro Ltd', sector: 'IT' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India', sector: 'FMCG' },
  { symbol: 'DIVISLAB.NS', name: 'Divi\'s Laboratories', sector: 'Pharma' },
  { symbol: 'DRREDDY.NS', name: 'Dr Reddy\'s Lab', sector: 'Pharma' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto', sector: 'Auto' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries', sector: 'FMCG' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'DABUR.NS', name: 'Dabur India', sector: 'FMCG' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries', sector: 'Chemicals' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints', sector: 'Paints' },
  { symbol: 'PAGEIND.NS', name: 'Page Industries', sector: 'Textiles' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', sector: 'IT' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree', sector: 'IT' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems', sector: 'IT' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis Ltd', sector: 'IT' },
  { symbol: 'COFORGE.NS', name: 'Coforge Ltd', sector: 'IT' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch Ltd', sector: 'Auto Ancillary' },
  { symbol: 'SCHAEFFLER.NS', name: 'Schaeffler India', sector: 'Auto Ancillary' },
  { symbol: 'TIMKEN.NS', name: 'Timken India', sector: 'Auto Ancillary' },
  { symbol: 'ELGIEQUIP.NS', name: 'Elgi Equipments', sector: 'Engineering' },
  { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton', sector: 'Engineering' },
  { symbol: 'CRISIL.NS', name: 'CRISIL Ltd', sector: 'Finance' },
  { symbol: 'DMART.NS', name: 'Avenue Supermarts', sector: 'Retail' },
  { symbol: 'TRENT.NS', name: 'Trent Ltd', sector: 'Retail' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge (India)', sector: 'Consumer Tech' },
  { symbol: 'IRCTC.NS', name: 'IRCTC', sector: 'Travel' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies', sector: 'Electronics' },
  { symbol: 'ABB.NS', name: 'ABB India', sector: 'Engineering' },
  { symbol: 'SIEMENS.NS', name: 'Siemens India', sector: 'Engineering' },
  { symbol: 'HONAUT.NS', name: 'Honeywell Automation', sector: 'Automation' },
  { symbol: 'SBICARD.NS', name: 'SBI Cards', sector: 'Finance' },
  { symbol: 'CDSL.NS', name: 'CDSL', sector: 'Finance' },
  { symbol: 'BSE.NS', name: 'BSE Ltd', sector: 'Finance' },
  { symbol: 'ANGELONE.NS', name: 'Angel One', sector: 'Finance' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', sector: 'Finance' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Finance', sector: 'Finance' },
  { symbol: 'MRF.NS', name: 'MRF Ltd', sector: 'Tyres' },
  { symbol: 'BAJAJHLDNG.NS', name: 'Bajaj Holdings', sector: 'Conglomerate' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharma', sector: 'Pharma' },
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories', sector: 'Pharma' },
  { symbol: 'IPCALAB.NS', name: 'IPCA Laboratories', sector: 'Pharma' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', sector: 'Conglomerate' },
  { symbol: 'TATACHEM.NS', name: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'LINDEINDIA.NS', name: 'Linde India', sector: 'Chemicals' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine', sector: 'Chemicals' },
  { symbol: 'SRF.NS', name: 'SRF Ltd', sector: 'Chemicals' },
  { symbol: 'ATUL.NS', name: 'Atul Ltd', sector: 'Chemicals' },
  { symbol: 'FINPIPE.NS', name: 'Finolex Industries', sector: 'Pipes' },
  { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries', sector: 'Plastics' },
  { symbol: 'ASTRAL.NS', name: 'Astral Ltd', sector: 'Pipes' },
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics', sector: 'Ceramics' },
  { symbol: 'CENTURYPLY.NS', name: 'Century Plyboards', sector: 'Building Materials' },
  { symbol: 'GOLDIAM.NS', name: 'Goldiam International', sector: 'Jewellery' },
  { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal', sector: 'Abrasives' },
  { symbol: 'SKFINDIA.NS', name: 'SKF India', sector: 'Bearings' },
  { symbol: 'NCC.NS', name: 'NCC Ltd', sector: 'Construction' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates', sector: 'Real Estate' },
  { symbol: 'PHOENIXLTD.NS', name: 'Phoenix Mills', sector: 'Real Estate' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties', sector: 'Real Estate' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty', sector: 'Real Estate' },
  { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises', sector: 'Real Estate' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India', sector: 'Electricals' },
  { symbol: 'HAVELLS.NS', name: 'Havells India', sector: 'Electricals' },
  { symbol: 'KAYNES.NS', name: 'Kaynes Technology', sector: 'Electronics' },
];

// ── Full combined universe ────────────────────────────────────────────────────
export const ALL_STOCKS = [...new Map(
  [...PENNY_STOCKS, ...MID_STOCKS, ...HIGH_STOCKS].map(s => [s.symbol, s])
).values()];

// Default price tiers
export const DEFAULT_TIERS = [
  { id: 'penny', label: 'Penny', min: 1, max: 399, emoji: '🪙', description: '₹1 – ₹399' },
  { id: 'mid', label: 'Mid', min: 400, max: 999, emoji: '📊', description: '₹400 – ₹999' },
  { id: 'high', label: 'High Value', min: 1000, max: Infinity, emoji: '💎', description: '₹1000+' },
] as const;

export type TierId = 'penny' | 'mid' | 'high' | 'custom';

export interface CustomRange {
  id: string;
  label: string;
  min: number;
  max: number;
  createdAt: string;
}

export function getStocksForTier(tierId: TierId, customRanges: CustomRange[] = [], customId?: string): StockMeta[] {
  if (tierId === 'penny') return PENNY_STOCKS;
  if (tierId === 'mid') return MID_STOCKS;
  if (tierId === 'high') return HIGH_STOCKS;
  // Custom: return full universe (filtered by price at scan time)
  return ALL_STOCKS;
}

export function symbolsForTier(tierId: TierId): string[] {
  return getStocksForTier(tierId).map(s => s.symbol);
}